      
//           <!-- Star Ratings (appears on hover) -->
//           <div class="mt-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center">
//             <div class="flex text-black">
//               <!-- Full stars -->
//               <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
//                 <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
//               </svg>
//               <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
//                 <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
//               </svg>
//               <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
//                 <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
//               </svg>
//               <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
//                 <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
//               </svg>
//               <!-- Half star -->
//               <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
//                 <path fill-rule="evenodd" d="M10 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" clip-rule="evenodd" />
//               </svg>
//             </div>
//             <span class="ml-1 text-xs text-black">(76)</span>
//           </div>


// //above from deepseek



// <div class="w-64 bg-white rounded-lg shadow-md overflow-hidden">
//   <div class="p-5 bg-gray-50 flex justify-center relative">
//     <img 
//       src="<%= image %>" 
//       alt="<%= name %>" 
//       class="h-40 object-contain drop-shadow-xl" 
//     />
//     <!-- Wishlist Icon -->
//     <button class="absolute top-3 right-3 h-8 w-8 flex items-center justify-center rounded-full bg-white shadow-md hover:bg-gray-50 transition-colors">
//       <svg 
//         xmlns="http://www.w3.org/2000/svg" 
//         width="16" 
//         height="16" 
//         viewBox="0 0 24 24" 
//         fill="none" 
//         stroke="currentColor" 
//         stroke-width="2" 
//         stroke-linecap="round" 
//         stroke-linejoin="round" 
//         class="text-gray-500 hover:text-red-500 transition-colors"
//       >
//         <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
//       </svg>
//     </button>
//   </div>
  
//   <div class="p-4 text-center">
//     <h3 class="font-bold text-gray-800 uppercase tracking-wide"><%= brand %></h3>
//     <p class="text-sm text-gray-600 mt-1"><%= name %></p>
    
//     <!-- Price section with discount -->
//     <div class="flex justify-center items-center mt-2 space-x-2">
//       <p class="text-xl font-semibold text-orange-500">$<%= price %></p>
//       <% if (originalPrice) { %>
//         <p class="text-sm text-gray-500 line-through">$<%= originalPrice %></p>
//       <% } %>
//     </div>
    
//     <div class="flex justify-center mt-2 space-x-1" id="star-rating-<%= id %>">
//       <!-- Stars will be generated by JavaScript -->
//     </div>
//   </div>
  
//   <div class="mt-2">
//     <button class="w-full bg-orange-500 hover:bg-orange-600 text-white font-semibold py-3 transition-colors">
//       ADD TO CART
//     </button>
//   </div>
// </div>

// <script>
//   document.addEventListener('DOMContentLoaded', function() {
//     const rating = <%= rating %>;
//     const starContainer = document.getElementById('star-rating-<%= id %>');
    
//     for (let i = 1; i <= 5; i++) {
//       const star = document.createElement('svg');
//       star.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
//       star.setAttribute('fill', 'currentColor');
//       star.setAttribute('viewBox', '0 0 24 24');
//       star.classList.add('w-4', 'h-4');
      
//       if (i <= rating) {
//         star.classList.add('text-black'); // Black stars for active rating
//       } else {
//         star.classList.add('text-gray-300');
//       }
      
//       star.innerHTML = '<path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />';
//       starContainer.appendChild(star);
//     }
//   });
// </script>

// above from lovable